[supervisord]
nodaemon=true

[program:php-fpm8.2]
command=/usr/sbin/php-fpm8.2 -c /etc/php/8.2/fpm/php-fpm.conf
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true

[program:mysql]
command=/usr/bin/pidproxy /var/run/mysqld/mysqld.pid /usr/sbin/mysqld
autostart=true

[program:redis]
command=/usr/bin/redis-server
autorestart=true

[program:crond]
command=/usr/sbin/crond -f -l 8
autostart=true
autorestart=true
startsecs=0
startretries=3
stderr_logfile=/var/log/crond.err.log
stdout_logfile=/var/log/crond.out.log
user=root
priority=10

[program:laravel-scheduler]
command=php /var/www/html/app/artisan schedule:work
directory=/var/www/html/app
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/log/scheduler.out.log
stderr_logfile=/var/log/scheduler.err.log
